//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
 */
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="them-color" content='white' />
        <link rel="manifest" href="manifest.json"/>
        <link rel="apple-touch-icon" href="icons/manifest-icon-192.maskable.png"/>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
